- name: Create Python3 venv & Install Packages
  pip:
    name:
      - requests
      - mysql-connector
      - wsgidav
      - cheroot
      - paramiko
      - impacket
      - kpcli
      - git+https://github.com/Pennyw0rth/NetExec
      - droopescan
      - git+https://github.com/adann0/multi_server
      - minikerberos
      - bloodyAD
    virtualenv: /home/kali/venv3
    virtualenv_python: python3
  become_user: kali
  become: yes

- name: Create Python3 venv & Install dirhunt
  pip:
    name:
      - dirhunt
    virtualenv: /home/kali/venv3_dirhunt
    virtualenv_python: python3
  become_user: kali
  become: yes
